name: urna
description: Projeto de Ciências.   

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  build_runner: any  


  cupertino_icons: ^1.0.2
  # sqflite: ^1.3.0 #stable version at the time of publishing this article
  # path_provider: ^1.6.7 #stable version at the time of publishing this article
  # sqflite: ^2.0.1 #stable version at the time of publishing this article
  # path_provider: ^2.0.11 #stable version at the time of publishing this article
  shared_preferences: ^2.0.15
  # just_audio: ^0.9.13
  audioplayers: ^1.0.1
  # audioplayers_windows: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # sqflite_common_ffi:    
  flutter_lints: ^2.0.0
  build_runner: any  

flutter:

  uses-material-design: true

  assets:
    - asset/img/
    - assets/sounds/
