name: Flutter Manual Scheduled
on:
  schedule:
    # cron: '30 5 * * 1'          
    cron: '12 * * * *'          

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3       
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
      - uses: ./.github/workflows/flutter-release.yml          