# name: Flutter Scheduled Release
on:
  schedule:
    - cron: '*/5 * * * *'
    # cron: '30 5 * * 1'          

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3       
      - name: Run a one-line script
        run: echo Hello, world!        
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
      - uses: ./.github/workflows/flutter-release.yml          